#!/usr/bin/env bash
# Generate llms-full.txt: the whole Lane OS documentation set concatenated into one
# file an agent can fetch in a single request. Regenerate after editing README/docs so
# it never drifts (do not hand-edit llms-full.txt). Run from the spine root.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=llms-full.txt
ORDER=(
  README.md
  docs/philosophy.md
  docs/architecture.md
  docs/write-lane-invariant.md
  docs/session-lifecycle.md
  docs/memory.md
  docs/multi-machine.md
  docs/code-from-anywhere.md
  docs/getting-started.md
)

{
  echo "# Lane OS - full documentation"
  echo
  echo "Generated by scripts/build-llms-full.sh from README.md + docs/. Do not edit by hand."
  echo
  for f in "${ORDER[@]}"; do
    [ -f "$f" ] || continue
    echo "================================================================"
    echo "FILE: $f"
    echo "================================================================"
    echo
    cat "$f"
    echo
    echo
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes)"
