#!/usr/bin/env python3
"""One budget table for every state file that a session reads whole.

WHY A TABLE AND NOT A PROSE RULE
--------------------------------
The four files loaded into every session (the constitution, the memory index,
ACTIVE_NOW, CONCERNS) each had a written brevity rule. Measured over four months in the
spine this was built in, the two with a byte ceiling were flat or smaller; the two
governed by prose alone had grown 2x and 5.2x, and startup load had gone from 31k to
81k characters. The failure was never carelessness. It was an ungated rule.

So every file a session reads whole is budgeted in ONE place, and every consumer reads
that place: `audit-cheap.sh` Check 4 at commit time, and any scheduled job you point at
it. A second copy of the thresholds is how two gates drift apart.

THRESHOLD POLICY
----------------
A check that fails the next unrelated commit gets disabled, not obeyed. So:

  * `fail` exists only for the files that load into EVERY session, where the cost is
    paid by every lane before it is asked anything.
  * everything else is `warn` only. Which file needs an archival pass, and what in it is
    still current, is lane judgment.
  * set new thresholds ABOVE today's legitimate reading, so the check catches a runaway
    rather than nagging about a file that is merely large on purpose.

CODE REPOS TOO
--------------
A code lane's own instruction files are read at the start of every session there, so
they carry budgets from the same table. `DECISIONS.md` is charged only for the text
above its `## Archive` divider, because that is all a session reads. `AGENTS.md` is
generated by the rules sync and is deliberately not budgeted: its size is the
constitution's problem, gated there.

USAGE
-----
    check-file-budgets.py                 human report, every tracked file
    check-file-budgets.py --over-only     only the findings
    check-file-budgets.py --json          machine-readable
    check-file-budgets.py --quiet         print nothing, exit code only

Exit codes: 0 nothing over, 1 a warn-level finding, 2 a hard-ceiling breach.
Env: LANE_OS_BUDGET_ROOT points the table at another tree (the self-test uses it);
LANE_OS_WORKSPACE_ROOTS is a colon-separated list of dirs holding code repos.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO = Path(os.environ.get("LANE_OS_BUDGET_ROOT") or Path(__file__).resolve().parents[1])

# (glob, warn, fail-or-None, why it is read whole)
BUDGETS: list[tuple[str, int, int | None, str]] = [
    # ---- loaded into EVERY session. The only rows with a hard ceiling.
    ("global/CLAUDE.md", 24_000, 40_000, "the rules, loaded every session on every lane"),
    ("memory/MEMORY.md", 20_000, None, "the memory index, injected every session"),
    ("brain/ACTIVE_NOW.md", 14_000, 24_000, "cross-project priorities, loaded every session"),
    ("brain/CONCERNS.md", 22_000, 36_000, "open worries, loaded every session"),
    # ---- read whole on demand by a spine session.
    ("brain/DECISIONS.md", 100_000, None, "never pruned by age, because an old decision still binds"),
    ("brain/PEOPLE.md", 60_000, None, "read whenever a person comes up"),
    ("brain/WEEKLY_LOG.md", 24_000, None, "a 2-week window by its own rule, so it should never grow"),
    ("brain/WHO_I_AM.md", 24_000, None, "identity and working style, read by the orient skills"),
    # ---- per-lane state.
    ("projects/*/STATUS.md", 32_000, None, "session state; over budget a session greps it instead of reading it"),
    ("projects/*/MEMORY.md", 32_000, None, "durable lane facts; read BEFORE asserting one, so it is read whole"),
    ("desks/*/LOG.md", 60_000, None, "desk history, appended forever"),
    ("desks/*/CLAUDE.md", 12_000, None, "the desk contract, read first in every desk session"),
]

# The aggregate matters on its own: the real cost is the sum a session pays before it is
# asked anything.
ALWAYS_LOADED = ["global/CLAUDE.md", "memory/MEMORY.md", "brain/ACTIVE_NOW.md", "brain/CONCERNS.md"]
AGGREGATE_WARN = 78_000
AGGREGATE_FAIL = 104_000

# (file, warn, why) inside each code lane's repo. Warn only.
CODE_REPO_BUDGETS: list[tuple[str, int, str]] = [
    ("CLAUDE.md", 25_000, "read at the start of every session in that repo; mechanism only"),
    ("BACKLOG.md", 20_000, "the queue, read whole when picking up work"),
    ("DECISIONS.md", 30_000, "the half above `## Archive`, which is what a session reads first"),
]
ARCHIVE_DIVIDER = "## Archive"


def workspace_roots() -> list[Path]:
    env = os.environ.get("LANE_OS_WORKSPACE_ROOTS")
    if env:
        return [Path(p).expanduser() for p in env.split(":") if p]
    return [Path.home() / "repos", Path.home() / "work"]


def read_first_size(path: Path) -> int:
    """Characters a session actually reads. For DECISIONS.md that is the text above the
    archive divider, since the file's own header tells the reader to stop there."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if path.name == "DECISIONS.md":
        head, sep, _ = text.partition("\n" + ARCHIVE_DIVIDER)
        if sep:
            return len(head)
    return len(text)


def size_of(path: Path) -> int:
    """Characters, not bytes. A budget about context cost is about characters."""
    return len(path.read_text(encoding="utf-8", errors="replace"))


def code_repo_rows() -> list[dict]:
    """A lane with a projects/ dir and a sibling git checkout under a workspace root."""
    rows: list[dict] = []
    for lane_dir in sorted(REPO.glob("projects/*")):
        if lane_dir.is_symlink() or not lane_dir.is_dir() or lane_dir.name.startswith("_"):
            continue
        for root in workspace_roots():
            repo = root / lane_dir.name
            if not (repo / ".git").exists():
                continue
            for name, warn, why in CODE_REPO_BUDGETS:
                f = repo / name
                if not f.is_file():
                    continue
                chars = read_first_size(f)
                rows.append({
                    "file": f"{repo.parent.name}/{lane_dir.name}/{name}",
                    "chars": chars, "warn": warn, "fail": None,
                    "level": "warn" if chars > warn else "ok", "why": why,
                })
            break
    return rows


def measure() -> dict:
    rows: list[dict] = []
    for pattern, warn, fail, why in BUDGETS:
        matches = sorted(REPO.glob(pattern)) if "*" in pattern else (
            [REPO / pattern] if (REPO / pattern).exists() else [])
        for path in matches:
            if path.is_symlink() or not path.is_file():
                continue
            # projects/ may carry alias symlinks to the same lane. The FILE is not a
            # symlink, its directory is, so skip by the alias and report the canonical
            # path once.
            if any((REPO / rel).is_symlink() for rel in path.relative_to(REPO).parents
                   if str(rel) != "."):
                continue
            if "_TEMPLATE" in path.parts:
                continue
            chars = size_of(path)
            level = "ok"
            if fail is not None and chars > fail:
                level = "fail"
            elif chars > warn:
                level = "warn"
            rows.append({"file": str(path.relative_to(REPO)), "chars": chars, "warn": warn,
                         "fail": fail, "level": level, "why": why})

    rows.extend(code_repo_rows())

    total = sum(size_of(REPO / n) for n in ALWAYS_LOADED if (REPO / n).exists())
    agg_level = "fail" if total > AGGREGATE_FAIL else "warn" if total > AGGREGATE_WARN else "ok"
    aggregate = {"file": "(the 4 always-loaded files, summed)", "chars": total,
                 "warn": AGGREGATE_WARN, "fail": AGGREGATE_FAIL, "level": agg_level,
                 "why": "every lane pays this before it is asked anything"}
    rows.append(aggregate)
    return {"rows": rows, "aggregate": aggregate}


def worst(rows: list[dict]) -> int:
    if any(r["level"] == "fail" for r in rows):
        return 2
    if any(r["level"] == "warn" for r in rows):
        return 1
    return 0


def human(rows: list[dict], over_only: bool) -> str:
    out = []
    shown = [r for r in rows if r["level"] != "ok"] if over_only else rows
    width = max((len(r["file"]) for r in shown), default=10)
    rank = {"fail": 2, "warn": 1, "ok": 0}
    for r in sorted(shown, key=lambda r: (-rank[r["level"]], -r["chars"])):
        ceiling = r["fail"] if r["fail"] is not None and r["level"] == "fail" else r["warn"]
        mark = {"fail": "OVER CEILING", "warn": "over budget", "ok": "ok"}[r["level"]]
        pct = round(100 * r["chars"] / ceiling)
        out.append(f"  {r['file']:<{width}}  {r['chars']:>7,} chars  {pct:>3}% of {ceiling:,}  {mark}")
        if r["level"] != "ok":
            out.append(f"  {'':<{width}}  -> {r['why']}")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--over-only", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    data = measure()
    rows = data["rows"]
    code = worst(rows)
    if args.json:
        print(json.dumps(data, indent=2))
    elif not args.quiet:
        report = human(rows, args.over_only)
        if report:
            print(report)
        elif args.over_only:
            print("  every tracked state file is inside its budget")
    return code


if __name__ == "__main__":
    raise SystemExit(main())
